name: fyrtel
description: "Fyrtel App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # multimedia
  video_player: ^2.9.2
  flutter_svg: ^2.0.14
  material_symbols_icons: ^4.2789.0

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7

  # DI
  get_it: ^7.2.0
  injectable: ^2.1.0

  # storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # other
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  pixel_perfect: ^1.1.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  json_serializable: ^6.8.0

  build_runner: ^2.0.0
  freezed: ^2.2.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.1.4

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/video/